#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.6.8 on Tue Apr  5 18:02:40 2016
#

# This is an automatically generated file.
# Manual changes will be overwritten without warning!

import wx
import gettext
from RoverFrame import RoverFrame

class RoverApp(wx.App):
	def OnInit(self):
		wx.InitAllImageHandlers()
		RoverClientGUI = RoverFrame(None, wx.ID_ANY, "")
		self.SetTopWindow(RoverClientGUI)
		RoverClientGUI.Show()
		return 1

# end of class RoverApp

if __name__ == "__main__":
	gettext.install("rvclient") # replace with the appropriate catalog name

	rvclient = RoverApp(0)
	rvclient.MainLoop()